// Code generated by "stringer -type=MatchUpdateType"; DO NOT EDIT.

package dissect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kill-0]
	_ = x[Death-1]
	_ = x[DBNO-2]
	_ = x[DefuserPlantStart-3]
	_ = x[DefuserPlantComplete-4]
	_ = x[DefuserDisableStart-5]
	_ = x[DefuserDisableComplete-6]
	_ = x[LocateObjective-7]
	_ = x[OperatorSwap-8]
	_ = x[Battleye-9]
	_ = x[PlayerLeave-10]
	_ = x[Other-11]
}

const _MatchUpdateType_name = "KillDeathDBNODefuserPlantStartDefuserPlantCompleteDefuserDisableStartDefuserDisableCompleteLocateObjectiveOperatorSwapBattleyePlayerLeaveOther"

var _MatchUpdateType_index = [...]uint8{0, 4, 9, 13, 30, 50, 69, 91, 106, 118, 126, 137, 142}

func (i MatchUpdateType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MatchUpdateType_index)-1 {
		return "MatchUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatchUpdateType_name[_MatchUpdateType_index[idx]:_MatchUpdateType_index[idx+1]]
}
